// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RESTApi.Models;

namespace RESTApi.Migrations
{
    [DbContext(typeof(ArtDBContext))]
    partial class ArtDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RESTApi.Models.Artikel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlantHoogte")
                        .HasColumnType("int");

                    b.Property<int>("PotMaat")
                        .HasColumnType("int");

                    b.Property<int>("kleur")
                        .HasColumnType("int");

                    b.Property<int>("productGroep")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Artikels");
                });
#pragma warning restore 612, 618
        }
    }
}
